# 全局配置文件
spring:
  application:
    name: ai-interviewer
  profiles:
    active: dev # dev-开发环境，prod-生产环境，test-测试环境 根据后缀区分不同环境配置文件
  servlet:
    multipart:
      max-file-size: 10MB    # 单个文件最大上传大小
      max-request-size: 10MB  # 单次请求最大上传大小

server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # 上传文件大小无限制

#日志级别
logging:
  level:
    root: info


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      banner: false
      update-strategy: not_empty
  mapper-locations: classpath*:/mapper/*.xml

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true
